ROS_VERSION: 2
SESSION_MANAGER: local/friday:@/tmp/.ICE-unix/2869,unix/friday:/tmp/.ICE-unix/2869
GZ_SIM_RESOURCE_PATH: /opt/ros/jazzy/share
QT_ACCESSIBILITY: 1
COLORTERM: truecolor
XDG_CONFIG_DIRS: /etc/xdg/xdg-ubuntu:/etc/xdg
XDG_MENU_PREFIX: gnome-
GNOME_DESKTOP_SESSION_ID: this-is-deprecated
CONDA_EXE: /home/marcelo/miniconda3/bin/conda
_CE_M: 
ROS_PYTHON_VERSION: 3
TERMINATOR_DBUS_PATH: /net/tenshu/Terminator2
GNOME_SHELL_SESSION_MODE: ubuntu
SSH_AUTH_SOCK: /run/user/1000/keyring/ssh
GZ_CONFIG_PATH: /opt/ros/jazzy/opt/gz_sim_vendor/share/gz:/opt/ros/jazzy/opt/sdformat_vendor/share/gz:/opt/ros/jazzy/opt/gz_gui_vendor/share/gz:/opt/ros/jazzy/opt/gz_transport_vendor/share/gz:/opt/ros/jazzy/opt/gz_rendering_vendor/share/gz:/opt/ros/jazzy/opt/gz_plugin_vendor/share/gz:/opt/ros/jazzy/opt/gz_fuel_tools_vendor/share/gz:/opt/ros/jazzy/opt/gz_msgs_vendor/share/gz:/opt/ros/jazzy/opt/gz_common_vendor/share/gz
ISAACSIM_PATH: /home/marcelo/isaacsim
MEMORY_PRESSURE_WRITE: c29tZSAyMDAwMDAgMjAwMDAwMAA=
TERMINATOR_UUID: urn:uuid:9012a209-6e71-4da2-a019-10fbaaf50fd5
XMODIFIERS: @im=ibus
DESKTOP_SESSION: ubuntu
GTK_MODULES: gail:atk-bridge
PWD: /opt/ros/jazzy/share/ros_gz_sim/launch
LOGNAME: marcelo
XDG_SESSION_DESKTOP: ubuntu
XDG_SESSION_TYPE: x11
GPG_AGENT_INFO: /run/user/1000/gnupg/S.gpg-agent:0:1
SYSTEMD_EXEC_PID: 2937
XAUTHORITY: /run/user/1000/gdm/Xauthority
GJS_DEBUG_TOPICS: JS ERROR;JS LOG
WINDOWPATH: 2
HOME: /home/marcelo
USERNAME: marcelo
LANG: en_US.UTF-8
LS_COLORS: rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.avif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:*~=00;90:*#=00;90:*.bak=00;90:*.crdownload=00;90:*.dpkg-dist=00;90:*.dpkg-new=00;90:*.dpkg-old=00;90:*.dpkg-tmp=00;90:*.old=00;90:*.orig=00;90:*.part=00;90:*.rej=00;90:*.rpmnew=00;90:*.rpmorig=00;90:*.rpmsave=00;90:*.swp=00;90:*.tmp=00;90:*.ucf-dist=00;90:*.ucf-new=00;90:*.ucf-old=00;90:
XDG_CURRENT_DESKTOP: ubuntu:GNOME
MEMORY_PRESSURE_WATCH: /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/session.slice/org.gnome.Shell@x11.service/memory.pressure
VTE_VERSION: 7600
AMENT_PREFIX_PATH: /home/marcelo/Developer/pegasus/install/pegasus:/home/marcelo/Developer/pegasus/install/mavlink_interface:/home/marcelo/Developer/pegasus/install/autopilot_controllers:/home/marcelo/Developer/pegasus/install/thrust_curves:/home/marcelo/Developer/pegasus/install/static_trajectories:/home/marcelo/Developer/pegasus/install/static_trajectory_manager:/home/marcelo/Developer/pegasus/install/pid:/home/marcelo/Developer/pegasus/install/pegasus_console:/home/marcelo/Developer/pegasus/install/autopilot_modes:/home/marcelo/Developer/pegasus/install/pegasus_utils:/home/marcelo/Developer/pegasus/install/pegasus_demos:/home/marcelo/Developer/pegasus/install/estimator_manager:/home/marcelo/Developer/pegasus/install/box_geofencing:/home/marcelo/Developer/pegasus/install/autopilot:/home/marcelo/Developer/pegasus/install/pegasus_msgs:/home/marcelo/Developer/pegasus/install/pegasus_gz:/home/marcelo/Developer/pegasus/install/mocap_interface:/home/marcelo/Developer/pegasus/install/mocap_emulator:/home/marcelo/Developer/pegasus_external/install/vrpn_vendor:/home/marcelo/Developer/pegasus_external/install/micro_xrce_vendor:/home/marcelo/Developer/pegasus_external/install/mavsdk_vendor:/home/marcelo/Developer/pegasus_external/install/casadi_vendor:/opt/ros/jazzy
CMAKE_PREFIX_PATH: /home/marcelo/Developer/pegasus/install/pegasus:/home/marcelo/Developer/pegasus/install/autopilot_controllers:/home/marcelo/Developer/pegasus/install/thrust_curves:/home/marcelo/Developer/pegasus/install/static_trajectories:/home/marcelo/Developer/pegasus/install/static_trajectory_manager:/home/marcelo/Developer/pegasus/install/pid:/home/marcelo/Developer/pegasus/install/pegasus_console:/home/marcelo/Developer/pegasus/install/autopilot_modes:/home/marcelo/Developer/pegasus/install/pegasus_utils:/home/marcelo/Developer/pegasus/install/box_geofencing:/home/marcelo/Developer/pegasus/install/pegasus_msgs:/home/marcelo/Developer/pegasus/install/pegasus_gz:/home/marcelo/Developer/pegasus/install/mocap_interface:/home/marcelo/Developer/pegasus/install/mocap_emulator:/home/marcelo/Developer/pegasus_external/install/vrpn_vendor:/home/marcelo/Developer/pegasus_external/install/micro_xrce_vendor:/home/marcelo/Developer/pegasus_external/install/mavsdk_vendor:/home/marcelo/Developer/pegasus_external/install/casadi_vendor:/opt/ros/jazzy/opt/gz_sim_vendor:/opt/ros/jazzy/opt/gz_sensors_vendor:/opt/ros/jazzy/opt/gz_physics_vendor:/opt/ros/jazzy/opt/sdformat_vendor:/opt/ros/jazzy/opt/gz_gui_vendor:/opt/ros/jazzy/opt/gz_transport_vendor:/opt/ros/jazzy/opt/gz_rendering_vendor:/opt/ros/jazzy/opt/gz_plugin_vendor:/opt/ros/jazzy/opt/gz_fuel_tools_vendor:/opt/ros/jazzy/opt/gz_msgs_vendor:/opt/ros/jazzy/opt/gz_common_vendor:/opt/ros/jazzy/opt/gz_math_vendor:/opt/ros/jazzy/opt/gz_utils_vendor:/opt/ros/jazzy/opt/gz_tools_vendor:/opt/ros/jazzy/opt/gz_ogre_next_vendor:/opt/ros/jazzy/opt/gz_dartsim_vendor:/opt/ros/jazzy/opt/gz_cmake_vendor
ROS_AUTOMATIC_DISCOVERY_RANGE: SUBNET
COLCON_PREFIX_PATH: /home/marcelo/Developer/pegasus/install:/home/marcelo/Developer/pegasus_external/install
INVOCATION_ID: 7309fd20932b410fbd9e319fe6697fd9
TERMINATOR_DBUS_NAME: net.tenshu.Terminator23558193cd9818af7fe4d2c2f5bd9d00f
MANAGERPID: 2523
GJS_DEBUG_OUTPUT: stderr
XDG_ACTIVATION_TOKEN: gnome-shell/Terminator/2937-5-friday_TIME2581978
_CONDA_EXE: /home/marcelo/miniconda3/bin/conda
LESSCLOSE: /usr/bin/lesspipe %s %s
_CONDA_ROOT: /home/marcelo/miniconda3
XDG_SESSION_CLASS: user
PYTHONPATH: /home/marcelo/Developer/pegasus/build/pegasus_demos:/home/marcelo/Developer/pegasus/install/pegasus_demos/lib/python3.12/site-packages:/home/marcelo/Developer/pegasus/install/pegasus_msgs/lib/python3.12/site-packages:/opt/ros/jazzy/lib/python3.12/site-packages
TERM: xterm-256color
_CE_CONDA: 
ISAACSIM_PYTHON: /home/marcelo/isaacsim/python.sh
LESSOPEN: | /usr/bin/lesspipe %s
USER: marcelo
CONDA_SHLVL: 0
CLUTTER_DISABLE_MIPMAPPED_TEXT: 1
DISPLAY: :1
SHLVL: 1
GSM_SKIP_SSH_AGENT_WORKAROUND: true
QT_IM_MODULE: ibus
CONDA_PYTHON_EXE: /home/marcelo/miniconda3/bin/python
LD_LIBRARY_PATH: /home/marcelo/Developer/pegasus/install/autopilot_controllers/lib:/home/marcelo/Developer/pegasus/install/thrust_curves/lib:/home/marcelo/Developer/pegasus/install/static_trajectories/lib:/home/marcelo/Developer/pegasus/install/static_trajectory_manager/lib:/home/marcelo/Developer/pegasus/install/pid/lib:/home/marcelo/Developer/pegasus/install/autopilot_modes/lib:/home/marcelo/Developer/pegasus/install/box_geofencing/lib:/home/marcelo/Developer/pegasus/install/pegasus_msgs/lib:/home/marcelo/Developer/pegasus_external/install/vrpn_vendor/lib:/home/marcelo/Developer/pegasus_external/install/mavsdk_vendor/lib:/home/marcelo/Developer/pegasus_external/install/casadi_vendor/lib:/opt/ros/jazzy/opt/gz_sim_vendor/lib:/opt/ros/jazzy/opt/gz_sensors_vendor/lib:/opt/ros/jazzy/opt/gz_physics_vendor/lib:/opt/ros/jazzy/opt/sdformat_vendor/lib:/opt/ros/jazzy/opt/rviz_ogre_vendor/lib:/opt/ros/jazzy/lib/x86_64-linux-gnu:/opt/ros/jazzy/opt/gz_gui_vendor/lib:/opt/ros/jazzy/opt/gz_transport_vendor/lib:/opt/ros/jazzy/opt/gz_rendering_vendor/lib:/opt/ros/jazzy/opt/gz_plugin_vendor/lib:/opt/ros/jazzy/opt/gz_fuel_tools_vendor/lib:/opt/ros/jazzy/opt/gz_msgs_vendor/lib:/opt/ros/jazzy/opt/gz_common_vendor/lib:/opt/ros/jazzy/opt/gz_math_vendor/lib:/opt/ros/jazzy/opt/gz_utils_vendor/lib:/opt/ros/jazzy/opt/gz_tools_vendor/lib:/opt/ros/jazzy/opt/gz_ogre_next_vendor/lib:/opt/ros/jazzy/opt/gz_dartsim_vendor/lib:/opt/ros/jazzy/opt/gz_cmake_vendor/lib:/opt/ros/jazzy/lib
XDG_RUNTIME_DIR: /run/user/1000
DEBUGINFOD_URLS: https://debuginfod.ubuntu.com 
LC_ALL: en_US.UTF-8
JOURNAL_STREAM: 9:37526
XDG_DATA_DIRS: /usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
PATH: /opt/ros/jazzy/opt/gz_msgs_vendor/bin:/opt/ros/jazzy/opt/gz_tools_vendor/bin:/opt/ros/jazzy/opt/gz_ogre_next_vendor/bin:/opt/ros/jazzy/bin:/home/marcelo/miniconda3/condabin:/home/marcelo/.local/bin:/home/marcelo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/marcelo/.local/bin:/home/marcelo/.local/bin
GDMSESSION: ubuntu
DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
ISAACSIM: /home/marcelo/isaacsim/isaac-sim.sh
PX4_DIR: /home/marcelo/Developer/PX4-Autopilot
ROS_DISTRO: jazzy
GIO_LAUNCHED_DESKTOP_FILE_PID: 12311
GIO_LAUNCHED_DESKTOP_FILE: /usr/share/applications/terminator.desktop
OLDPWD: /home/marcelo/Developer/pegasus
_: /opt/ros/jazzy/bin/ros2
PX4_SIM_MODEL: gz_x500
PX4_GZ_STANDALONE: 1
PX4_GZ_MODEL_NAME: x500
PX4_SYS_AUTOSTART: 4001
PX4_GZ_WORLD: racetrack